services:
  postiz-app:
    build: .
    container_name: postiz-app
    restart: always
    expose:
      - "80"
      - "3000"
    environment:
      - DATABASE_URL=postgresql://postiz-user:${POSTGRES_PASSWORD}@postiz-postgres:5432/postiz-db
      - REDIS_URL=redis://postiz-redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_JWT_SECRET=${REFRESH_JWT_SECRET}
      - FRONTEND_URL=http://localhost
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost
      - BACKEND_URL=http://localhost:3000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3000
    depends_on:
      - postiz-postgres
      - postiz-redis
    networks:
      - postiz-network

  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postiz-network

  postiz-redis:
    image: redis:7-alpine
    container_name: postiz-redis
    restart: always
    networks:
      - postiz-network

volumes:
  postgres-volume:

networks:
  postiz-network:
